config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "lists#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :lists, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :participations, only: [:new, :create]
  end

  namespace :participants do
    resources :lists, only: [:show, :index]
  end

  resources :gifts, only: [:index, :update]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :list
  belongs_to :giver, class_name: 'User', foreign_key: 'giver_id', inverse_of: :gifts, optional: true

  has_many_attached :images

  enum status: {available: 0, booked: 1, bought: 2}
  validates :name, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id', inverse_of: :lists

  enum status: {open: 0, closed: 1}

  has_many :users, through: :participations
  has_many :gifts, dependent: :destroy, inverse_of: :list
  has_many :participations

  accepts_nested_attributes_for :gifts,
                                allow_destroy: true,
                                reject_if: proc {|att| att['name'].blank? }

  validates :name, uniqueness: true
  validates :name, presence: true

  def default_status
    0 if status.nil?
  end

  def default_name
    "Ma Liste de Nöel" if name.nil?
  end

end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :participations
  has_many :lists, through: :participations
  has_many :owner_lists, class_name: "List", inverse_of: :owner, foreign_key: :owner

  has_many :gifts, inverse_of: :giver

  def full_name
    "#{first_name} #{last_name}"
  end

  after_create :send_welcome_email

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @gifts = Gift.where(giver: current_user)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new]

  def index
    @lists = List.where(owner: current_user)
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
    @gift = Gift.new
  end

  def create
    @list = List.new(list_params)
    @list.owner = current_user
    @list.status = 0
    @list.name = "Ma Liste de Nöel #{current_user.owner_lists.size}"
    if @list.save

      redirect_to new_list_participation_path(@list)
      flash[:notice] = "Votre liste a été créé avec succés"
    else
      render 'lists/new'
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(lists_params)
      flash[:notice] = 'Votre Liste de Noël a bien été mise à jour'
      redirect_to lists_path
    else
      render 'lists/edit'
    end
  end

  private

  def list_params
    params
      .require(:list)
      .permit(:name,:owner_id,
        gifts_attributes: [:id, :_destroy, :name, :description, :brand, :link, images: []])
  end

end

app/controllers/my/lists_controller.rb
class My::ListsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new]

  def index
    @lists = List.where(owner: current_user)
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
    @gift = Gift.new
  end

  def create
    @list = List.new(list_params)
    @list.owner = current_user
    @list.default_status
    @list.default_name

    if @list.save
      redirect_to my_list_participation(@list)
      flash[:notice] = "Votre liste a été créé avec succés"
    else
      render 'my/lists#new'
    end
  end

  private

  def list_params
    params
      .require(:list)
      .permit(:name,:owner_id,
        gifts_attributes: [:id, :_destroy, :name, :description, :brand, :link])
  end

end

app/controllers/my_community/lists_controller.rb
class MyCommunity::ListsController < ApplicationController


  def index
    @lists = current_user.lists
  end

  def show
    @list = List.find(params[:id])
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @list = List.new
  end
end

app/controllers/participants/lists_controller.rb
class Participants::ListsController < ApplicationController


  def index
    @lists = current_user.lists
  end

  def show
    @list = List.find(params[:id])
  end


end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

  def new
    @participation = Participation.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gifts/index.html.erb
<h1>Mes achats de Noël</h1>

<ul>
  <% @gifts.each do |gift| %>
    <li>
      <%= "#{gift.name} pour #{gift.list.owner.full_name}" %>
      <% gift.images.each do |image| %>
        <%= image_tag image %> <br />
      <% end %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> <%= yield(:title) || "Mahotte.fr" %></title>
    <meta name="description" content="<%=(yield(:description) || "").squish %>" >
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div class="wrapper-horizontal hidden-xs">
      <%= render "shared/banner" %>
      <div class="container-fluid list_form">
        <%= yield %>
      </div>
    </div>

    <div class="hidden-sm hidden-md hidden-lg">
      <div class="banner-xs" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/mahotte/image/upload/v1529138299/woodgrain-with-christmas-ornaments_4460x4460.jpg');">
        <div class="banner-content">
          <h1>Mahotte.fr</h1>
          <p class="text-right">Gardez la magie de noël</p>
        </div>
      </div>
      <div class="container-fluid list_form">
        <%= yield %>
      </div>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>


 <%# content_for(:title) do%><!--
#   <%#= @restaurant.name %> est sur Mahotte.fr
# <%# end %> -->

app/views/lists/_form.html.erb
<%= simple_form_for @list, url: lists_path do |f| %>
  <%= f.error_notification %>

  <h4>Ma liste de Nöel</h4>
  <p>Cher Père Nöel, ayant été trés sage cette année, je voudrais ...</p>

  <div id="gifts">
    <%= f.simple_fields_for :gifts, @gift do |builder| %>
       <%= render 'gift_fields', f: builder %>
    <% end %>

    <div class="links">
      <%= link_to_add_association 'Ajouter un cadeau', f, :gifts, class: 'btn btn-primary' %>
    </div>
  </div>
  <%= f.submit 'Envoyer ma liste', class: "btn-success" %>
<% end %>

app/views/lists/_gift_fields.html.erb
<div class="nested-fields">
    <%= f.input :name, placeholder: "Un Cadeau dans ma hotte", label: false %>
    <%= f.input :description, placeholder: "Quelques détails sur le cadeau", label: false %>
    <%= f.input :brand, placeholder: "Une marque spécifique ?",label: false %>
    <%= f.input :link, placeholder: "Lien internet... https://www.fnac.com....",label: false %>
    <%= f.file_field :images, multiple: true, placeholder: "Une image pour être sûr ",label: false, accept: 'images/png,images/gif,images/jpeg' %>
    <%= link_to_remove_association "Supprimer un Cadeau", f, class: 'btn btn-primary btn-xs' %>
</div>

app/views/lists/edit.html.erb
 <%= render "lists/form", list: @list %>

app/views/lists/index.html.erb
<h1>Ma Hotte </h1>

<ul>
<% @lists.each do |list| %>
  <li>
    <%= list.name %>
    <%= link_to edit_list_path(list) do %>
      <i class="fa fa-user"></i>
    <% end %>
  </li>
<% end %>

</ul>

app/views/lists/new.html.erb
    <%= render "lists/form", list: @list, url: lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<ul>
<% @list.gifts.each do |gift| %>
  <li>
    <%= gift.name %>
    <%= gift.brand unless gift.brand.present? %>
    <%= gift.description %>
    <% gift.images.each do |image| %>
      <%= image_tag image %> <br />
    <% end %>
  </li>
<% end %>
</ul>

app/views/my/lists/_form.html.erb
<%= simple_form_for @list, url: my_lists_path do |f| %>
  <%= f.error_notification %>

  <h4>Ma liste de Nöel</h4>
  <p>Cher Père Nöel, ayant été trés sage cette année, je voudrais ...</p>


  <div id="gifts">
    <%= f.simple_fields_for :gifts, @gift do |builder| %>
       <%= render 'gift_fields', f: builder %>
    <% end %>

    <div class="links">
      <%= link_to_add_association 'Ajouter un cadeau', f, :gifts, class: 'btn btn-primary' %>
    </div>
  </div>
  <%= f.submit 'Envoyer ma liste', class: "btn-success" %>
<% end %>

app/views/my/lists/index.html.erb
<h1>Ma Hotte </h1>

<ul>
<% @lists.each do |list| %>
  <li>
    <%= list.name %>
    <%= link_to my_list_path(list) do %>
      <i class="fa fa-user"></i>
    <% end %>
  </li>
<% end %>

</ul>

app/views/my_community/lists/index.html.erb
<h1>Ma communauté</h1>

<ul>
 <% @lists.each do |list| %>
  <li>
    <%= "#{list.owner.full_name}" %>
    <%= link_to my_community_list_path(list) do %>
      <i class="fa fa-user"></i>
    <% end %>
  </li>
 <% end %>
</ul>

app/views/participants/lists/index.html.erb
<h1>Ma communauté</h1>

<ul>
 <% @lists.each do |list| %>
  <li>
    <%= "#{list.owner.full_name}" %>
    <%= link_to participants_list_path(list) do %>
      <i class="fa fa-user"></i>
    <% end %>
  </li>
 <% end %>
</ul>

app/views/participants/lists/show.html.erb
<h1><%= "Liste de Nöel de #{@list.owner.full_name}" %></h1>

<ul>
 <% @list.gifts.each do |gift| %>
  <li>
    <%= "#{gift.name}" %>
    <%= gift.brand %>
    <%= gift.description %>

  </li>
 <% end %>
</ul>

app/views/participations/new.html.erb
<h1>Vos Peres noel</h1>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/mahotte/image/upload/v1529138299/woodgrain-with-christmas-ornaments_4460x4460.jpg');">
  <div class="banner-content">
    <h1>Mahotte.fr</h1>
    <p class="text-right">Gardez la magie de noël</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Avec <i class="fa fa-heart"></i> pour garder la magie de Noël
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.svg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Ma Hotte", lists_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Ma Communauté", participants_lists_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Mes Achats de Noël", gifts_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">

        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Mon Profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fas fa-book"></i> Mode d'emploi
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Me Déconnecter") %>
              <% end %>
            </li>
          </ul>
        </div>

      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Mode d'emploi", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Me Connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Créer un Compte"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li><%= link_to "Ma Hotte", lists_path %></li>
          <li>
            <%= link_to participants_lists_path do %>
                Ma Communauté
              <% end %>
          </li>
          <li>
            <%= link_to "Mes achats de Nöel", gifts_path %></li>
          <li>
            <%= link_to "#" do %>
              <%= t(".profile", default: "Mon Profil") %>
            <% end %>
          </li>
          <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Me Déconnecter") %>
              <% end %>
          </li>
        <% else %>
            <!-- Login link (when logged out) -->
          <li><%= link_to "Mode d'emploi", "#" %></li>
          <li><%= link_to t(".sign_in", default: "Me Connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to t(".sign_in", default: "Créer un Compte"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>